gui:
  tabWidth: 2
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
customCommands:
  - key: "D"
    context: "files"
    command: "echo 'You do not want to do this.'"
